### ISSUE TITLE
unit_test_wavefunction failing on OSX llvm7

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#965] opened 2018-08-09 15:06 UTC
This appears to be a regression going back to at least to commit a60be2091d0775524fa38b8cfc08dd0018fb08a7

**Comment by prckent** [comment] 2018-11-08 16:14
Is this problem still reproducible and still important? It does not show up on other platforms and I can't reproduce it on OSX.

Using Apple Clang I am unable to build due to cmake not finding the C++14 standard library (have not tried to fix this). cmake v3.12.4 from macports:
```
pk7$ /usr/bin/clang -v
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
pk7$ cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DQMC_MPI=0 ../qmcpack/
```
Will fail our on C++14 standard library check.

Using a macports installed clang 6.0.1:
pk7$ clang++ -v
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-6.0/bin
pk7$ cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DQMC_MPI=0 ../qmcpack/ ; make -j 4
...
pk7$ ctest -R deterministic-unit_test_wavefunction
Test project /Users/pk7/projects/qmc/git_QMCPACK_prckent/build_osx
    Start 11: deterministic-unit_test_wavefunction
1/1 Test #11: deterministic-unit_test_wavefunction ...   Passed    0.08 sec

I get the same results with a macports installed clang 7.0.0.
```
pk7$ cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DQMC_MPI=0 ../qmcpack/
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
...
pk7$ ctest -R deterministic-unit_test_wavefunction
Test project /Users/pk7/projects/qmc/git_QMCPACK_prckent/build_osx
    Start 11: deterministic-unit_test_wavefunction
1/1 Test #11: deterministic-unit_test_wavefunction ...   Passed    0.16 sec
```

**Comment by markdewing** [comment] 2018-11-08 16:33
This might have been addressed by #1075 #1087 #1091

Those were driven by clang 6 and 7 on linux

**Comment by prckent** [comment] 2018-11-08 16:37
Probable.

**Comment by PDoakORNL** [comment] 2018-11-08 16:41
So I propose we no longer support apple's clang and this is closed.

**Comment by prckent** [comment] 2018-11-08 16:49
Our apple instructions say to use macports or brew. We do correctly pickup veclib. I also propose that we don't worry further about apple clang until (say) a prospective user enquires with good reason.

**Closed by prckent** 2018-11-08 16:49 UTC
Labels: bug
