### ISSUE TITLE
Memory Leak for spline_m

### ISSUE THREAD

**Issue by ddinge** [QMCPACK/qmcpack#3002] opened 2021-03-09 17:17 UTC
The ddt debugger is showing a memory leak for spline_m for the det_hf_vmc_LiH-gamma test problem(see attached). I've looked with the ddt and totalview debuggers and it looks as though the MultiBspline destructor is never invoked. 

Could someone with knowledge of the code take a look at this?

[LiH_solid_1x1x1_ppleak-report logbook.pdf](https://github.com/QMCPACK/qmcpack/files/6110239/LiH_solid_1x1x1_ppleak-report.logbook.pdf)

**Comment by ye-luo** [comment] 2021-03-09 17:25
This was due to a design issue of the current production drivers. The high level code never clean up the "clones". We will not fix the current production driver but instead the batched drivers should have this issue being resolved by designing the life time of objects more properly.

**Comment by prckent** [comment] 2021-03-09 22:03
Dennis - Just concurring with Ye here - unless there is an easy fix (likely no), it is better for us to focus on the new batched drivers (and therefore e.g. the *vmcbatch* and *dmcbatch* deterministic tests). These should be clean and hopefully the destructor is invoked. Please check there. In practice the splines should only ever be destructed at the end of the simulation so even though they leak in the old drivers it is not a concern for production runs. It is however a concern as far as the general memory cleanliness of the application.

**Closed** 2021-03-09 23:46 UTC
Labels: bug, wontfix
