### ISSUE TITLE
Building with Intel compiler

### ISSUE THREAD

**Issue by afernandezody** [QMCPACK/qmcpack#2320] opened 2020-02-25 16:46 UTC
Hello QMCPACK Team,
I was trying to build QMCPACK using the Intel compiler 19.1 (20200117) and CUDA support. I upgraded to the latest release (3.9.1) but it's still telling me that it only supports releases ending in 0 (15.0, 16.0, 17.0, 18.0, 19.0). The full error reads:

```
[  0%] Building NVCC (Device) object src/einspline/CMakeFiles/einspline.dir/einspline_generated_bspline_create_cuda.cu.o
In file included from /usr/local/cuda-10.2/include/cuda_runtime.h(83),
                 from /home/ubuntu/qmcpack-3.9.1/src/einspline/bspline_create_cuda.cu(0):
/usr/local/cuda-10.2/include/crt/host_config.h(110): error: #error directive: -- unsupported ICC configuration! Only ICC 15.0, ICC 16.0, ICC 17.0, ICC 18.0 and ICC 19.0 on Linux x86_64 are supported!
  #error -- unsupported ICC configuration! Only ICC 15.0, ICC 16.0, ICC 17.0, ICC 18.0 and ICC 19.0 on Linux x86_64 are supported!
   ^

CMake Error at einspline_generated_bspline_create_cuda.cu.o.RELEASE.cmake:217 (message):
  Error generating
  /home/ubuntu/qmcpack-3.9.1/build/src/einspline/CMakeFiles/einspline.dir//./einspline_generated_bspline_create_cuda.cu.o

src/einspline/CMakeFiles/einspline.dir/build.make:70: recipe for target 'src/einspline/CMakeFiles/einspline.dir/einspline_generated_bspline_create_cuda.cu.o' failed
make[2]: *** [src/einspline/CMakeFiles/einspline.dir/einspline_generated_bspline_create_cuda.cu.o] Error 1
CMakeFiles/Makefile2:2525: recipe for target 'src/einspline/CMakeFiles/einspline.dir/all' failed
make[1]: *** [src/einspline/CMakeFiles/einspline.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Due to unrelated reasons, it's not easy for me to downgrade to icc 19.0 so I was wondering if there is way to go around this problem or if this wil be tackled in future releases.
Thanks.

**Comment by prckent** [comment] 2020-02-25 16:57
Closing since a duplicate of #2319

**Closed by prckent** 2020-02-25 16:57 UTC
