### ISSUE TITLE
Core dump at checkpoint

### ISSUE THREAD

**Issue by anbenali** [QMCPACK/qmcpack#162] opened 2017-03-28 05:08 UTC
I will not have time to investigate this but I have all the files and core dump. It goes as follow:

- Run VMC correctly.
- Run DMC with a checkpoint every 20 blocks. Runs nicely the first 20 blocks and dies with the following error message:
2017-03-28 01:30:14.206 (INFO ) [0x400016334e0] 1395:tatu.runjob.monitor: tracklib completed
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

The stack points at:

000000000108a3c0
00000012.long_branch_r2off._ZNSt8ios_base4InitD1Ev+0
/soft/applications/qmcpack/github/src/QMCDrivers/QMCDriver.cpp:446

Which corresponds to :
RandomNumberControl::write(RootName,myComm);

**Comment by ye-luo** [comment] 2017-03-28 14:47
std::bad_alloc means not enough memory.

**Comment by prckent** [comment] 2017-03-28 14:49
When reporting crashes, please give details of the run. e.g. electron count, size of spline buffers, machine etc. Then we will be able to tell if this is a small reproducible run or will need to be cut down conveniently debug.

**Comment by prckent** [comment] 2017-03-28 14:54
The checkpointing implementation should consider memory usage - it is better to be slow and reliable than run out of memory and crash.

**Comment by ye-luo** [comment] 2017-06-01 03:40
This issue is confirmed. Impact both read and write.
Random number IO is handled on MPI rank 0. mt19937 save 624 4-byte integer per thread.
Assuming using 16384 node with 32 threads each, need 1.2 GB memory.
It is fixable and has nothing to do with hdf5.
Currently the RN are store in *.random.xml. I don't like xml for such large files.
Since there is an h5 implementation, I only need to parallelize it.

The electron configuration is already handled in parallel. No issue in principle.

**Comment by prckent** [comment] 2017-08-28 21:15
Fixed by #320 ?

**Comment by ye-luo** [comment] 2017-08-28 21:32
I would like to close these issues after the nightly tests tonight.

**Comment by ye-luo** [comment] 2017-08-30 13:32
PHDF5 is working well in the nightly tests.

**Closed by ye-luo** 2017-08-30 13:32 UTC
Labels: bug
