### ISSUE TITLE
Nexus example tests failing on oxygen and other systems

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#1028] opened 2018-08-23 15:58 UTC
One example
 https://cdash.qmcpack.org/CDash/testDetails.php?test=2533958&build=27324

```
Test name     : example_gamess_H2O
Test exception: 
  example script failed to run
  attempted command: ./h2o_pp_hf.py --generate_only --sleep=0.01
  location: /scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/build_gcc_mkl_soa/nexus/tests/.nexus_test/user_examples/gamess/H2O
Test backtrace:
  File "/scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/executables/ntest", line 469, in run
    self.operation(**self.op_inputs)
  File "/scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/executables/ntest", line 1825, in user_examples
    nfail('example script failed to run\nattempted command: {0}\nlocation: {1}'.format(command,path))

Test status: fail
```

**Comment by jtkrogel** [comment] 2018-08-23 16:02
These tests pass when run manually.  The problem might be a failure to install Nexus on the test machine.

**Comment by jtkrogel** [comment] 2018-08-23 16:10
Perhaps this can be done by assigning PYTHONPATH explicitly in nexus/tests/CMakeLists.txt.

**Comment by jtkrogel** [comment] 2018-08-23 16:10
I will try to reproduce and fix.

**Comment by markdewing** [comment] 2018-08-23 16:15
In addition to fixing the tests, ntest could be updated to make the problem more obvious.  When the execute call (around line 1823) fails, the stdout and stderr from the failed call should be printed out.   If the problem is that Nexus not installed, that would show up as a failed import in the script output.

**Comment by jtkrogel** [comment] 2018-09-24 12:54
The problem appears to be fixed with #1083.  Nexus tests are passing on CDash on oxygen and on the other testing platforms I looked at.

Agree?

**Comment by ye-luo** [comment] 2018-09-24 14:19
Please wait for another night because it is hard to read the results from oxygen due to errors generated by compiler changes. Sunday oxygen results are very limited.

**Comment by prckent** [comment] 2018-09-24 14:36
Ignore all oxygen results for the time being. I am debugging changes in the scripts and compiler versions.

**Comment by jtkrogel** [comment] 2018-11-28 18:15
This is fully resolved now.  Closing.

**Closed by jtkrogel** 2018-11-28 18:15 UTC
Labels: bug
