### ISSUE TITLE
Problem in scaling the number of nodes on OLCF/Summit using the batched offload code

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/qmcpack#3899] opened 2022-03-09 15:41 UTC
**Describe the bug**
I am seeing a strange issue with scaling to a large number of nodes using the offload code. When I run with a few or a small number of nodes, the VMC and DMC steps go through and there are no problems. However, if I increase the number of nodes significantly without changing the ranks/node or resources/node, then qmcpack can't load the shared libraries and the job fails. So I am not actually sure if this problem is due to qmcpack or related to Summit. I am attaching a tar which includes successful 1 and 2 node jobs and a failed 4096 node job. Note that only the number of nodes change between these runs.

**To Reproduce**
1. Latest release of qmcpack (Last git commit: 3c6e832288af59a383b83d743fd6071e372b162e)
2. Use the script to build `qmcpack/config/build_olcf_summit_Clang.sh`
3. See the attached tar file for full job script and inputs

**Expected behavior**
One should be able to debug the input for a few node jobs and then increase the number of nodes without failures.

**System:**
 - system name: OLCF/Summit
 - modules loaded: See job output files
 - Material: alpha-RuCl3, cation, large supercell with 32 chemical units.

[issue_offload.tar.gz](https://github.com/QMCPACK/qmcpack/files/8215894/issue_offload.tar.gz)

**Comment by ye-luo** [comment] 2022-03-09 16:04
I saw failed shared library loading in the past even in 1 node runs. Unfortunately this is a pure machine problem.
What happens under `jsrun qmcpack` is the following.
1. jsrun launch qmcpack on every node like a normal executable.
2. OS handles dynamic library searching of qmcpack on each node.
3. dynamic library cannot be found on the search locations. I think one node doesn't have a file system properly loaded.
The dynamic libraries causing trouble are located at `/ccs/proj/mat151/opt/llvm/main-20220304/lib`
Email OLCF helpdesk and ask if the that file system is unreliable.

Code wise I don't think there is anything we can do.

**Comment by ye-luo** [comment] 2022-03-10 16:16
> I moved the llvm module to my gpfs system and that resolves the failed library loading problem.
It doesn't solve the problem. The libomp.so still lives under `/ccs`. You were just lucky this time.

I will need to take a closer look at the failure.

**Comment by ye-luo** [comment] 2022-03-10 17:42
By the way, did you try the executables I deployed on Summit?

**Comment by aannabe** [comment] 2022-03-10 19:25
I tried some time ago with an older release and I was seeing similar issues with a large number of nodes. I can try with a recent one if that's helpful.

**Comment by ye-luo** [comment] 2022-03-10 19:30
The latest one is from March 4th.

**Comment by aannabe** [comment] 2022-03-11 16:48
FYI, the executables from March 4 runs for 1 node but also crashed for 4096 nodes (attached).

[0304_4096.tar.gz](https://github.com/QMCPACK/qmcpack/files/8233682/0304_4096.tar.gz)

**Comment by ye-luo** [comment] 2022-03-11 18:48
It doesn't seem to be a crash but qmcpack didn't start due to the file system issue.

**Comment by aannabe** [comment] 2022-04-25 17:12
Thanks to Ye's investigations, this issue is essentially resolved. The problem originated from libomptarget OpenMP offload runtime library, which was buggy in the most recent version. Compiling with a release version resolved it. However, we do see problematic scaling in time for ~ 4k number of nodes:
```
NODES	TIME_mins
1	15.3
512	16.5
1024	17.3
4096	156.1
```
Ye's runs also show similar behavior: similar run-times up to 2k nodes and much slower for 4k.
Currently, I don't know the source of this problematic scaling, and it needs another investigation.

**Comment by ye-luo** [comment] 2022-04-25 17:15
To be precise, libomptarget itself was OK. The one I initially built was faulty when using bootstrap clang from develop. Once I rebuild libomptarget with GCC, the crashing problem went away.

**Comment by ye-luo** [comment] 2022-04-25 17:26
Here is my VMC time from the second block.
```
# node count  block time(sec)
16    2.59
32    2.61
64    2.63
128   2.64
256   2.57
512  36.5
1024  2.69
2048  3.81
4096 27.3
```
When doing such runs, there are other jobs still on going. The huge variability can be caused by other jobs with demanding network traffic or there are misbehaving nodes being allocated to the job.

**Comment by prckent** [comment] 2022-04-25 17:39
I don't think

**Comment by prckent** [comment] 2022-04-25 17:44
I have reopened this issue. I think we should only close it when we have either one report of sensible scaling or we have at least pinpointed the problem and made a more specific follow-up issue. The observed variation is not acceptable - hopefully we can correctly blame the machine and file a bug. 

I am particularly worried by the bad scaling of the VMC time reported by Ye. Since the time is for a single block, that points to a misbehaving node. There should be no variability with busyness of the system due to the negligible communications or I/O in VMC. It would still be a problem in DMC but would be more understandable.

Ye, can you please rerun to investigate the reproducibility? If it is just a ghost we can close, but if repeatable we should look into e.g. getting our OLCF liaison to investigate.

**Comment by jtkrogel** [comment] 2022-04-25 18:57
Is this pattern reproducible in the cpu only legacy code?  That should at least discriminate w.r.t. possible network congestion.

**Comment by ye-luo** [comment] 2022-04-25 19:26
@prckent A new issue to track the variability  https://github.com/QMCPACK/qmcpack/issues/3974

**Closed by ye-luo** 2022-04-25 19:26 UTC
