### ISSUE TITLE
LMY_ENGINE creatings its own complex type

### ISSUE THREAD

**Issue by naromero77** [QMCPACK/qmcpack#534] opened 2017-12-05 04:41 UTC
In some face-to-face to discussions with @ye-luo, it seemed necessary to create this GitHib issue.

This is a subtle bug that is triggered in the Spack environment when selecting Intel-MKL for BLAS+LAPACK and the GCC compiler. It may be harder to reproduce with pure CMake, but all that is needed is to link against Intel-MKL libraries but NOT include the Intel-MKL header files.

Below is the error:
```
[ 10%] Building CXX object src/formic/utils/CMakeFiles/formic_utils.dir/lapack_interface.cpp.o
cd /private/var/folders/q5/2qkr385166q8pvvpxz8dhrt00000gn/T/naromero/spack-stage/spack-stage-gjpgoq/qmcpack/spack-build/src/formic/utils && /Users/naromero/spack/lib/spack/e\
nv/gcc/g++  -DADD_ -DH5_USE_16_API -DHAVE_CONFIG_H -DHAVE_LMY_ENGINE -DINLINE_ALL=inline -DUSE_REAL_STRUCT_FACTOR -Drestrict=__restrict__ -I/Users/naromero/spack/opt/spack/d\
arwin-sierra-x86_64/gcc-7.2.0/fftw-3.3.6-pl2-pv3kyz4bpis55xmyfggwzke54x5qk4ua/include -I/Users/naromero/spack/opt/spack/darwin-sierra-x86_64/gcc-7.2.0/libxml2-2.9.4-rbcmuybu\
vvnyw26petiq2pkyurwsoajz/include/libxml2 -I/Users/naromero/spack/opt/spack/darwin-sierra-x86_64/gcc-7.2.0/hdf5-1.10.1-drgvy6lvlrg4zred3u6jjs54ath6wzeb/include -I/Users/narom\
ero/spack/opt/spack/darwin-sierra-x86_64/gcc-7.2.0/zlib-1.2.11-phh3tamqrylis4ljv5u2wdh6cahpz3wi/include -I/Users/naromero/spack/opt/spack/darwin-sierra-x86_64/gcc-7.2.0/boos\
t-1.65.1-fyi4p36ztdrjrrc4jx7v2qairjylqs4k/include -I/Users/naromero/spack/var/spack/stage/qmcpack-3.2.0-7k7lapxrofl6wo6oynbjpe5eznig4i5t/qmcpack/src -I/private/var/folders/q\
5/2qkr385166q8pvvpxz8dhrt00000gn/T/naromero/spack-stage/spack-stage-gjpgoq/qmcpack/spack-build/src -I/private/var/folders/q5/2qkr385166q8pvvpxz8dhrt00000gn/T/naromero/spack-\
stage/spack-stage-gjpgoq/qmcpack/spack-build/include  -std=c++11  -fopenmp -fomit-frame-pointer -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -D__forceinline=inli\
ne -Wno-deprecated -march=native -O2 -g -DNDEBUG -ffast-math   -o CMakeFiles/formic_utils.dir/lapack_interface.cpp.o -c /Users/naromero/spack/var/spack/stage/qmcpack-3.2.0-7\
k7lapxrofl6wo6oynbjpe5eznig4i5t/qmcpack/src/formic/utils/lapack_interface.cpp
In file included from /private/var/folders/q5/2qkr385166q8pvvpxz8dhrt00000gn/T/naromero/spack-stage/spack-stage-gjpgoq/qmcpack/spack-build/src/formic/utils/declare.h:4:0,
                 from /Users/naromero/spack/var/spack/stage/qmcpack-3.2.0-7k7lapxrofl6wo6oynbjpe5eznig4i5t/qmcpack/src/formic/utils/lapack_interface.cpp:2:
/Users/naromero/spack/var/spack/stage/qmcpack-3.2.0-7k7lapxrofl6wo6oynbjpe5eznig4i5t/qmcpack/src/formic/utils/declare_mkl.h:4:10: fatal error: mkl_types.h: No such file or d\
irectory
 #include <mkl_types.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

The problem is that this code is creating its own complex type by using the mkl_types.h header file, rather than using the complex type provided by the main QMCPACK code. 

Contents of `declare_mkl.h` below:
```
#ifndef FORMIC_LAPACK_DECLARE_MKL_HEADER
#define FORMIC_LAPACK_DECLARE_MKL_HEADER

#include <mkl_types.h>
#define MKL_Complex16 std::complex<double>
typedef std::complex<double> xcomplex;
#include<mkl.h>

#define FORMIC_HAVE_MKL


#endif
```
As far as the Spack package is concerned, I may just deactivate the optimizer for now and later own backport a patch once the issue is fixed.

**Comment by prckent** [comment] 2017-12-05 13:57
Why the invalid tag?

Why does FORMIC have any MKL dependence at all? Is this not the real bug, or is it a workaround for MKL related "issues"?

**Comment by ye-luo** [comment] 2017-12-05 16:01
formic has a set of MKL wrappers which should be removed and use the ones QMCPACK provide.

**Comment by markdewing** [comment] 2017-12-05 16:01
formic calls blas functions (like dgemv), which is why it depends on MKL.

The formic MKL include wrapper sets the MKL complex type so MKL doesn't define it's own complex type, as in https://software.intel.com/en-us/mkl-linux-developer-guide-using-complex-types-in-c/c

The real-space part of the qmcpack code doesn't ever include mkl.h, it just defines the interfaces in Blasf.h.  This why the code can link with MKL libraries without including the MKL headers.

**Comment by markdewing** [comment] 2017-12-05 16:07
How is spack getting into a situation where the environment directs qmcpack to link with MKL, but not use the include files?  We can only get away keeping the blas/lapack function declarations inside QMCPACK because the BLAS interface is pretty standard.

AFQMC will also have a problem with this situation - it really will need the MKL headers since the sparse routines are not as standardized as BLAS.

**Comment by naromero77** [comment] 2017-12-05 20:14
@prckent I was not sure whether this should be labeled as a bug or invalid. Since it does not cause a compile time or run time failure, it is not a bug per se -- but you should not be allowed to define your own data type if you are part of the main QMCPACK code IMO. Hence, I labelled it invalid. It should just be using blasf.h as @ye-luo @markdewing indicated. I think this is right thing to do.

@markdewing Spack is its own environment in a very real sense, but it goes it steps further... They don't want CMake to find LAPACK, BLAS, or any other critical library on its own. The library location, etc. must be passed in through the Spack library interface. Spack wants you to pass the Spack-detected (as opposed to CMake-detected) libraries via the following environment variables: `cmake -DLAPACK_FOUND=true -DLAPACK_LIBRARIES=<some value> -DLAPACK_INCLUDE_DIRS=<some value>`

For reasons which I don't understand, -DLAPACK_INCLUDE_DIRS is passed in but it does not get added into the INCLUDE directory, even though I have patched CMakeLists.txt to do so:
`INCLUDE_DIRECTORIES(${LAPACK_INCLUDE_DIRS})`

anyhow, that is what is going in Spack -- it is somewhat orthogonal to the main issue, but I wanted to provide a context.

**Comment by ye-luo** [comment] 2017-12-05 20:58
Someone submits an issue and claims it is a bug. After our assessment it is not a bug, we will tag the issue invalid and close the issue.

**Comment by naromero77** [comment] 2017-12-05 21:08
Thanks for the clarification.

**Closed** 2019-05-16 20:36 UTC
Labels: bug
