### ISSUE TITLE
AFQMC crashes with unexpected complex/real integral file

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2448] opened 2020-05-12 17:12 UTC
**Describe the bug**

Per user report on Google groups and subsequent discussion ( https://groups.google.com/forum/#!topic/qmcpack/2gGphvbBPyk ), the AFQMC code will crash if a real-valued compilation encounters an integral file with complex numbers. The AFQMC code should detect this (handle the HDF5 error or enquire of the file before reading) and give an appropriate error.  If the complex code can not load real valued files similar error handling should be added.

This is a bug more than a feature request because it is a very easy mistake to make and it should be handled gracefully. e.g. The real space code gives advice if a complex wavefunctions are needed for a specific twist.

**To Reproduce**

Develop. Example HDF5 file on https://groups.google.com/forum/#!topic/qmcpack/2gGphvbBPyk

**Expected behavior**

A meaningful error message and abort.

**System:**

Any

**Additional context**

None

**Comment by mmorale3** [comment] 2020-05-12 18:19
How hard is it to get the dimensions of the dataset without actually reading it?
I think there is a function right now that does it by reading the dataset, which
is too inefficient I think. If we can get dimensions easily, we can check before reading them
and would give us a chance to abort gracefully.

**Comment by fdmalone** [comment] 2020-05-12 18:33
The functions that exist throw errors which could be caught checkShapeConsistency

**Comment by ye-luo** [comment] 2020-05-12 18:46
It seems that you want a way to query the rank and size of each rank of a dataset. This can be exposed. We have internal check codes which never read the dataset but the metadata only.

My concern is that relying on querying the dimension of a particular dataset is not an optimal safey strategy.

**Comment by mmorale3** [comment] 2020-05-12 18:53
We can just catch the exceptions, this should be good enough for better error messages.
Having access to the actual dimensions could also be useful. We could read real data in the complex build if we know ahead of time that it is real. Can you expose them? We'll use them with caution.

**Comment by fdmalone** [comment] 2020-05-12 18:58
Ye's original suggestion to add a flag in the HDF5 would work too?

**Comment by mmorale3** [comment] 2020-05-12 19:05
We should do both. We can't guarantee that our tools are used to build the
input files.

**Comment by fdmalone** [comment] 2020-05-12 19:06
Good point.

**Comment by mmorale3** [comment] 2020-05-12 19:16
On the other hand, we can make it a requirement of the format.

**Comment by ye-luo** [comment] 2020-05-12 19:33
Multiple kinds of exception may occur, it is not safe to blindly thrust an error was caused by real/complex difference.

Reading real and then used as complex doesn't require you to know the actually rank of dataset. The rank difference is caused by data type which is managed by hdf_archive not outside.

I went through the logic of hdf_archive. It makes sense to expose user ranks and their sizes. This is more related to memory.

getRankAndSize(aname) is not OK. hdf_archive should be type aware.
getRankAndSize<T>(aname) is OK and it should strictly validate the rank sizes related to T.
So your case should still fail when trying to read double from complex<double> which must have last dimension size 2. But this not the right logic for your case.

Your case is a type safety violation and you cannot distinguish std::complex<double> a and std::vector<double> a(2) merely based on the dataset in h5 file. So you are required to make a type flag in h5.

**Comment by mmorale3** [comment] 2020-05-12 19:42
getRankAndSize<T>(aname) would work for us. 
Regarding exceptions, you can always make a custom exception for this.

**Comment by mmorale3** [comment] 2020-05-12 19:43
That was meant to be getRankAndSize <T> (aname)

**Comment by mmorale3** [comment] 2020-05-12 19:43
arrrgggg
The one that takes a template parameter

**Comment by ye-luo** [comment] 2020-05-12 20:16
The function has been implemented already https://github.com/QMCPACK/qmcpack/blob/b970dac6c2404370c06a129ac053e06c4d135bca/src/io/hdf_archive.h#L171
I'm going to make a PR for a bit more explanation but you don't need to wait for me.

**Comment by fdmalone** [comment] 2020-05-13 17:12
Following #2450 we now need to check internally that the integral type matches the build type, at least for real builds and complex integrals.

**Comment by fdmalone** [comment] 2020-05-16 00:09
Should be fixed with #2460

**Closed by fdmalone** 2020-05-16 00:09 UTC
Labels: bug
