### ISSUE TITLE
Final DMC energy varies with equilibration strategy

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2330] opened 2020-03-05 17:11 UTC
The final DMC energy for a 20 atom cell of SrCoO3 differs when QMCPACK is run in two ways that should be equivalent:

1. A single DMC run with a timestep of 0.002/Ha.
2. DMC run first with a timestep of 0.02/Ha followed by 0.002/Ha.

In this case, a difference of 6.6(7) mHa/f.u. is observed in the final DMC energy using the CPU code on Theta (case 1) and CADES (case 1 and 2) with Theta and CADES agreeing for case 1.

A plot of the 2-timestep data with differing numbers of equilibration blocks removed, seems to show a very long and slow transient.  For comparison, a full equilibration from VMC to the DMC 0.002/Ha equilibrium occurs within 100 blocks.  Starting from the 0.02/Ha equilibrium, the new 0.002/Ha equilibrium is not reached even after 1000 blocks.

![GS4_ediff](https://user-images.githubusercontent.com/24547905/76005030-75c4cc80-5ed8-11ea-8b55-b6892bed5f52.png)

Given the rapid equlibration from the high energy VMC state, it is unclear what mechanism could be responsible for the lack of equilibration from the lower energy, and presumably closer, DMC 0.02/Ha state.  More investigation of this effect is warranted.

The code's inability to relax to the same minimum from different initial states casts doubt on the equilibrium found from standard single shot calculations performed in production.

Issue identified by @mcbennet.

**Comment by prckent** [comment] 2020-03-05 20:42
Hoping to narrow this bug/feature: if you do a restart, does the problem persist?

**Comment by prckent** [comment] 2020-03-05 20:43
Attention @camelto2 . Until resolved, this issue would preclude a smarter equilibration strategy.

**Comment by camelto2** [comment] 2020-03-05 20:48
> Attention @camelto2 . Until resolved, this issue would preclude a smarter equilibration strategy.

Agreed. I've been chatting with @mcbennet about this offline. @lshulen and @rcclay have pointed out a number of issues that could be the culprit similar to what you mention above.

**Comment by jtkrogel** [comment] 2020-03-05 20:49
This is for T-moves version 0.  Trying a restart is a good idea.  Right now, we are performing reruns on CADES with slightly smaller errorbars for 20, 10, and 5 atom cells as initial runs gave ambiguous results for the smaller cells.  This should tell us if the issue is reproducible and whether it appears for smaller systems as well.

The 20 atom runs take about a day on 8 Skylake nodes.

**Comment by jtkrogel** [comment] 2020-03-05 20:50
@camelto2, @lshulen, @rcclay What are your suggestions for possible culprits for this issue?

**Comment by camelto2** [comment] 2020-03-05 20:50
It is possibly worth mentioning that @aannabe has seen similar problems with an independent code (qwalk) using tmoves. The tmoves used there would be equivalent to tmoves v0 in qmcpack.

**Comment by rcclay** [comment] 2020-03-05 20:52
DMC propagator needs an E_trial and variance of E_local for things like adjusting the population size and determining if the walkers are stepping into weird places.  Depending on how these values are estimated/carried over between simulations could have some measureable consequences, especially for these energy scales.

**Comment by jtkrogel** [comment] 2020-03-05 20:52
Any data for methods other than T-moves v0 (i.e. is there any reason to believe this is local to T-moves)?

**Comment by jtkrogel** [comment] 2020-03-05 20:53
@rcclay, but these choices should fade out rapidly and should be no worse than starting from VMC (at least in principle), right?

**Comment by rcclay** [comment] 2020-03-05 20:55
I need to dig into SimpleFixedNodeBranch and see how precisely and how often we update this stuff.

**Comment by camelto2** [comment] 2020-03-05 21:00
> @camelto2, @aannabe Any data for methods other than T-moves v0 (i.e. is there any reason to believe this is local to T-moves)?

Not that I am aware of. If nothing is obvious from the propagator as @rcclay mentioned above, it would be useful to check the dependence on tmoves/locality

**Comment by camelto2** [comment] 2020-03-05 21:02
another thing to investigate is the whether or not you can recover the correct behavior using smaller jumps in the timestep. Rather than going from 0.02 to 0.002, trying a few intermediates to see if the problem is as drastic.

**Comment by jtkrogel** [comment] 2020-03-05 21:03
A complicating factor is that at the entry point to each DMC sub-run, warmup is performed with stochastic reconfiguration.  In this case (and in others), we have observed that the trial energy behaves erratically (rapid fluctuations on the scale of the VMC-DMC energy difference), before settling down immediately following the warmup.

If a large error was introduced to the trial energy at this point, and if the moving average of the trial energy kept this initial bias for a long time, it could affect the population dynamics for an extended period of time.  I suppose that this would formally appear as a more pronounced (and transient) population control bias.

**Comment by jtkrogel** [comment] 2020-03-05 21:06
@camelto2 I agree that this is a good thing to investigate.  I had planned to move this direction once we have fully settled reproducibility.  Restarts are another good thing to try early on.

**Comment by prckent** [comment] 2020-03-06 15:23
In view of the upcoming weekend it would be sensible to queue several independent series of runs that will tell us the most with the least amount of human effort. For example:

- Repeat these tests with the locality approximation to include/exclude t-moves as a source of problems. This is a few line change to the inputs.
- Repeat these tests using restarts and not multiple qmc sections. This is a bit more work to setup but will either exclude or implicate passing of state information between QMC sections as a factor. Add an additional dmc section so that you have a restarted section following a normal dmc section and not one with equilibration. The two production sections should have the same results and statistical behavior.

Perhaps this has already been done, but I think it is worth fishing for significant problems in existing data. Unlikely to be successful but low effort:

- Look at histograms of the existing 0.002 a.u. production data graphed above to see if by eye there are any outliers, changes in the distributions. They should be indistinguishable independent of starting point. 
- Check the acceptance statistics of the two 0.002 a.u. production results graphed above. They should be indistinguishable.

**Comment by jtkrogel** [comment] 2020-03-06 16:58
Chandler is performing a series of runs.  He's been able to reproduce the problem in the 10 atom cell, so we can now get conclusive results in 12 hours on 4 nodes.

Runs we have planned:

* Restart runs w/ 0.002 a.u. starting from walker populations equilibrated to 0.02/Ha and "equilibrated" to 0.002/Ha following 0.02.
* Runs with larger intermediate timestep: i.e. 0.04 -> 0.002 and 0.1 -> 0.002
* A run with an identical intermediate timestep 0.002 -> 0.002
* Running "adiabatically" 0.02->0.0199->0.0198...->0.002
* Runs for LA and T-moves versions 1 and 3 (version 0 used so far)

Additional observations:
* The 0.002 acceptance ratio agrees to high precision across all runs
* Differences in the energy sub-components reveal a pattern similar to "stuck walker" issues, i.e. a higher kinetic energy, a higher electron-electron energy, and a lower local electron-ion energy (more time spent in the core region).  The non-change of acceptance ratio is, however, inconsistent with "stuck walker" behavior.

**Comment by Hyeondeok-Shin** [comment] 2020-03-06 17:16
@jtkrogel @prckent I'm writing what I found today because it seems to be related with this issue.

 This DMC results are for 2D GeSe starting from 0.1, 0.05 and 0.01 to 0.005 a.u. time step, and v3 T-moves is used.

 I first thought DMC total energy is converted enough on 0.005 a.u., but when I restart with stored walkers on the same 0.005 a.u. final time step, it gives different equilibrium total energy.

![Bug](https://user-images.githubusercontent.com/24758789/76106068-bb969900-5f9b-11ea-839a-d68122dd014f.jpg)
 
I think it is the same issue with here.

**Comment by mcbennet** [comment] 2020-03-06 17:45
Hyendeok, interesting. The stored walkers that you use for the restart -- they were stored during the 0.005 a.u. timestep in the first run?

**Comment by Hyeondeok-Shin** [comment] 2020-03-06 17:53
@mcbennet Yes, it is. They were from the first run with the same time step 0.005 a.u. to the restart run.

**Comment by prckent** [comment] 2020-03-06 19:23
@Hyeondeok-Shin Have you checked that VMC restarts correctly and consistently in this system? Clearly it would be very difficult for it not to, but we thought DMC was safe as well...

**Comment by Hyeondeok-Shin** [comment] 2020-03-06 19:39
@prckent I didn't check for VMC restart run, but I can quickly check it. I'll post here when VMC check has done.

**Comment by Hyeondeok-Shin** [comment] 2020-03-07 01:57
I quickly did a restart test for VMC and it seems fine.

VMC test has done with total 400 blocks and 200 blocks + 200 restart blocks.

Total 400 blocks.
                                                   LocalEnergy               Variance           ratio
GeSe-S4-dmc  series 1  -105.390069 +/- 0.001767   2.487108 +/- 0.081797   0.0236

First 200 + 200 restart blocks.

                            LocalEnergy               Variance           ratio
file  series 2  -105.391064 +/- 0.001996   2.507822 +/- 0.072885   0.0238

They are equivalent, so restart works correctly for VMC (or single QMC section),

**Comment by prckent** [comment] 2020-03-09 15:12
@mcbennet @jtkrogel assuming that the weekend runs have not flagged a clear culprit, I have an additional request: compile the code without MPI and run on the smaller cell with OpenMP threads on one node only. The run should use exactly the same number of total walkers as the 4 node runs so that it can be directly compared. This will rule out any problems with either our MPI implementation or that on CADES.

**Comment by jtkrogel** [comment] 2020-03-09 16:14
The weekend runs have not flagged a clear culprit, however we do have some new information:

1. Running with a larger intermediate timestep magnifies the effect (much larger bias in the following small timestep run), making it easier to study the effect and/or look for it in other systems.
2. The magnitude of the effect can vary greatly with different initial seeds (one run might show a large effect and an exact rerun with a different see can show a much smaller effect).
3. The effect is still present in various T-moves variants, but possibly to varying degrees (possibly conflated with 2 though).  We are running now w/ a larger intermediate timestep to clarify.
4. Restarts "work", i.e. the effect is fully preserved across restarts.

We can run with no-mpi. Chandler is currently trying to compile v3.6.0 for a historical reference.  He will also soon see if the effect is visible in pseudopotential diamond, if so, we can more easily compare e.g. QMCPACK and QWalk in the near future (good to isolate code vs algorithm issue).

**Comment by ye-luo** [comment] 2020-03-09 16:28
@jtkrogel could you provide the DMC input sections and the full printout of QMCPACK corresponding to your run with two time steps?

**Comment by mcbennet** [comment] 2020-03-09 16:35
@ye-luo attached here
[equil_strategy.tar.gz](https://github.com/QMCPACK/qmcpack/files/4307828/equil_strategy.tar.gz)

**Comment by ye-luo** [comment] 2020-03-09 16:57
@mcbennet Could you rerun the one_ts and two_ts with warmupSteps=1000?

**Comment by mcbennet** [comment] 2020-03-09 17:05
Yes, I can have a look at that.

**Comment by prckent** [comment] 2020-03-09 17:19
Interesting results so far. Can you confirm that locality approximation shows the problem? I suggest focusing on it since all the different QMC codes have it implemented consistently.

**Comment by mcbennet** [comment] 2020-03-09 18:00
It is present also when LA is used. 
![la_transient](https://user-images.githubusercontent.com/1430804/76243146-3ebf2580-620e-11ea-8fd5-48cc8d282fb5.png)

**Comment by mcbennet** [comment] 2020-03-10 12:11
@prckent we have confirmed that the bias is still present when running without MPI. Additionally, this test was run on a separate machine which rules out the issue being "CADES" specific.

**Comment by mcbennet** [comment] 2020-03-10 19:06
@prckent No noticeable differences in the trace of the acceptance ratio or the histogram (other than the two-timestep case looks non-symmetric and weighted to the right -- due to shifting average). Histogram shown below in a.u.

![hist](https://user-images.githubusercontent.com/1430804/76349533-91691200-62e0-11ea-8fbe-08cbbf813807.png)

**Comment by prckent** [comment] 2020-03-10 19:37
Thanks. I don't see anything alarming here.

**Comment by mcbennet** [comment] 2020-03-12 13:36
For the last couple of days, I have been searching for this issue in other versions of the code (I originally ran with 3.8.9). Plotted below are a number of those runs. Signs are now pointing to the issue being a bug and not a feature. Additionally, it looks like 3.7.0 and 3.8.0 are perhaps bug free.

I have other runs that are coming down the pipe that use 400 blocks (400b in figure) for all the various versions given that we have found that this leads to a systematically large error in the 3.8.9 version of the code.

Furthermore, I have another run launched with a potential fix to the source which Ye suggests could perhaps be a solution.

[Issue2330_00.pdf](https://github.com/QMCPACK/qmcpack/files/4324422/Issue2330_00.pdf)

**Comment by jtkrogel** [comment] 2020-03-12 13:47
It is reassuring to see that all of the releases are OK when using a single timestep.  It is also good to see that only the most recent 3.9.1 release has the two timestep bug.  This strongly limits the impact of the bug in the wild.

**Comment by jtkrogel** [comment] 2020-03-12 13:49
A search to corner the bug from here should be straightforward.

**Comment by prckent** [comment] 2020-03-12 16:26
For once, a bug like this is good news. 

The hand-off between DMC blocks is presumably bad, and this area of the code was indeed refactored.

I suggest to make (and commit) a few step deterministic test with multiple DMC blocks. We have existing deterministic tests for DMC. Presumably old versions will pass this new test but not the current development version.

(Note that v3.8.9 is a random development version - you have to specify the git hash to be precise)

**Comment by mcbennet** [comment] 2020-03-12 17:05
For future reference, the commit hash corresponding to the 3.8.9 build I used was `25fddfc`.

**Comment by mcbennet** [comment] 2020-03-12 19:08
After searching through the commit history, I am seeing that #1759 (3.8.0) is bias free while the next merge, #1704, contains the bias.

The baseline energy that I see when running with a single timestep is:

E_correct = -449.350880 +/- 0.001515

The following energies correspond to the smaller timestep of a two-timestep run for the relevant commits:
E_1759 = -449.351889 +/- 0.001466
E_1704 = -449.210272 +/- 0.005003
E_Devel = -449.212618 +/- 0.001570

**Comment by jtkrogel** [comment] 2020-03-12 19:13
For reference, as commits, these are:
```
6abbff0b8       Tue Jul 23 12:24:35 2019 -0500  Merge pull request #1759 from QMCPACK/rc_380
955fb6c0a       Wed Jul 24 08:00:46 2019 -0400  Merge pull request #1704 from PDoakORNL/refactor_pre_unified_driver
```

**Comment by jtkrogel** [comment] 2020-03-12 19:15
Assigning this to @PDoakORNL and @ye-luo.  Anyone can feel free to change this if in disagreement.

**Comment by camelto2** [comment] 2020-03-12 19:22
So briefly staring at the code, a major difference between (other than the refactoring) #1759 and #1704 is that in most of the drivers, the resetComponents was removed. I haven't checked to see if the functionality was reimplemented elsewhere, but resetComponents seems to have been called when reusing a driver in a subsequent run, which would be relevant here

**Comment by prckent** [comment] 2020-03-12 20:09
It would be best for a deterministic test to be added by whoever has these different versions already compiled.

**Comment by jtkrogel** [comment] 2020-03-12 20:38
We apparently already have a deterministic DMC test with varying timesteps.  See #1764 by @Hyeondeok-Shin .  This test was added immediately following the introduction of the bug (2 days later), but used v3.6.0 to make the test.

If it really used 3.6.0 and the test is currently passing (did not check), then a deterministic test of this type might not be sufficient.

**Comment by jtkrogel** [comment] 2020-03-12 20:41
See also #1738.

**Comment by Hyeondeok-Shin** [comment] 2020-03-12 20:43
As @jtkrogel  pointed out, we already have multi DMC section deterministic test for diamond. I'm 
now testing with this input but using t-moves on the different versions, but this test is passing with 3.6.0, 3.7.0, 3.8.0, and 3.9.1. It seems hard to find that bug just for a few blocks for the deterministic test.

**Comment by Hyeondeok-Shin** [comment] 2020-03-12 21:11
I think bug can be reproduced in the deterministic test with larger drop of the time step.
It is hard to find with the time step change with 0.02 -> 0.01 -> 0.005, but if I do with 0.5 -> 0.005, DMC total energy reference on 0.005 becomes,

3.6.0 : -10.44060255
3.7.0 : -10.44060255
3.8.0 : -10.44060255
3.9.1 : -10.60770742  
 
I'll make the test with the references.

**Comment by jtkrogel** [comment] 2020-03-13 13:08
Really interesting that the error shows up this way with timestep.  Likely this means that the probability that a given walker trajectory is affected by the bug scales with timestep, i.e. most trajectories are fine at lower timestep jumps but not at larger ones.

It might implicate a changed threshold at 955fb6c0a, such as the timestep dependent thresholds that appear in `max` functions in the branching cutoff schemes.

**Comment by jtkrogel** [comment] 2020-03-13 17:51
I've just run @Hyeondeok-Shin's new test with AoS develop and it passes.

**Comment by jtkrogel** [comment] 2020-03-13 17:57
SoA develop fails.  Both AoS and SoA develop pass the original multi timestep test.

**Comment by prckent** [comment] 2020-03-13 18:34
Confirmed https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=bug-deterministic-diamondC_1x1x1_pp-vmc-dmc-lg_ts_sdj-1-1-2-totenergy&date=2020-03-13

**Comment by jtkrogel** [comment] 2020-03-13 18:48
Chandler is running the original bug case on AoS develop.  It will be interesting to see whether the bug really is local to SoA.

At present, I don't have good ideas on how a bug could have been introduced in SoA under the refactoring in #1704 without also having created one in AoS.

**Comment by jtkrogel** [comment] 2020-03-13 19:06
The above AoS pass is for the real code.  Complex AoS/SoA both fail.

**Comment by Hyeondeok-Shin** [comment] 2020-03-13 20:21
@jtkrogel Different DMC reference on large time step between real/complex code seems older issue than the first SoA real code issue. I saw the same failure on 3.6.0 SoA/AoS complex build.

**Comment by jtkrogel** [comment] 2020-03-13 20:50
Chandler and I are having some premonitions that the issue maybe more complex as well.  Chandler is currently running statistical tests of the original bug case across the following combinations: SoA/AoS, real/complex, 3.8.0/PR 1704/develop.

Hopefully this will add clarity.

**Comment by mcbennet** [comment] 2020-03-17 16:55
I have performed stochastic tests for two different systems, the original bug case and diamond 1x1x1.

**Original Bug Case (Complex WF)**

Reference energy from one timestep (SoA and AoS agree): **-449.351323 +/- 0.001461**

Table below shows the energies for various versions/builds from a 0.002/Ha timestep after running at a 0.1/Ha timestep for 10 blocks. 1704 is the problem commit identified before.

| Build | Two TS. 10 blocks. |
|-----------|-----------------------------------|
| 3.8.0 AoS |           -449.351626 +/- 0.004367 |
| 3.8.0 SoA |          -449.217068 +/- 0.003553 |
| 1704 AoS |          -449.204673 +/- 0.004556 |
| 1704 SoA |          -449.216200 +/- 0.003699 |
| Devel AoS |         -449.225601 +/- 0.004604 |
| Devel SoA |         -449.225293 +/- 0.007144 |

Table below shows the energies for various versions/builds from a 0.002/Ha timestep after running at a 0.1/Ha timestep for 400 blocks. Bias appears more uniform in this case.

| Build | Two TS. 400 blocks. |
|-----------|-----------------------------------|
| 3.8.0 AoS |        -449.348151 +/- 0.001823   |
| 3.8.0 SoA |        -449.210329 +/- 0.001364   |
| 1704 AoS |          -449.208976 +/- 0.002143 |
| 1704 SoA |          -449.210877 +/- 0.001656 |
| Devel AoS |         -449.210049 +/- 0.001859 |
| Devel SoA |         -449.211890 +/- 0.001428 |

**Diamond 1x1x1 Case**

First, for Hyeoneok's deterministic tests, I see the following across the various versions and builds

| Build |  Test Outcome |
|------|------------|
| 3.8.0 AoS real |  PASS |
| 3.8.0 SoA real |  PASS |
|  1704 AoS real |  PASS |
|  1704 SoA real |  PASS |
| Devel AoS real |  PASS |
| Devel SoA real |  FAIL |

For diamond, I also ran stochastic tests. For the same versions and builds (but also including complex builds), I ran single timestep runs (OneTS, 0.002/Ha) and two timestep runs (Two TS, 0.3/Ha -> 0.002/Ha). All runs use the same random seed. The results are summarized in the following figure

![Energies](https://user-images.githubusercontent.com/1430804/76879200-4b65fe00-684c-11ea-90e0-b30274b89ceb.png)
 
After discussion with Jaron, we suspect that there might actually be two bugs here. One related to the timestep and also one related to SoA, for instance, in the last figure the TwoTS SoA results differ between 1704 and Devel while the AoS results agree (seen also in the above deterministic tests).

**Comment by mcbennet** [comment] 2020-03-17 17:44
After looking through the code last week, I notice that a call is not made to resetRun for the SimpleFixedNodeBranch when it is used for consecutive DMC sections. I modified 1704 to include this call and the preliminary results are as follows for the original bug case:

Reference energy from one timestep (SoA and AoS agree): -449.351323 +/- 0.001461

1704_Mod AoS LocalEnergy           =  -449.353363 +/- 0.001590
1704_Mod SoA LocalEnergy           =  -449.210412 +/- 0.001392 

From this change to 1704, it appears that AoS is now bias free

I am performing similar stochastic tests for develop (which includes the resetRun call) for the original bug case and diamond 1x1x1 and will follow up soon.

**Comment by jtkrogel** [comment] 2020-03-17 18:01
Interesting.  According to the SCO runs, a bug was introduced at 1704 for AoS, while SoA is incorrect for 3.8.0 and before.  From the vantage point of diamond, a bug is introduced at 1704 for both AoS and SoA.

Still worth trying to fix whatever bug was introduced at 1704 and then see what remains.

**Comment by mcbennet** [comment] 2020-03-18 12:14
I see the following stochastic results for diamond with develop+modification mentioned above (DevMod).

![Energies](https://user-images.githubusercontent.com/1430804/76959484-0d221a80-68f0-11ea-9c09-b400e5fdcfca.png)

Also, for SCO, the modification appears to have resolved AoS.

One TS Ref: -449.351323 +/- 0.001461

AoS LocalEnergy           =  -449.350831 +/- 0.001897
SoA LocalEnergy           =  -449.212763 +/- 0.001374

I am submitting a WIP PR, so that others might test my modification, scrutinize it, etc.

**Comment by jtkrogel** [comment] 2020-03-18 12:46
Thanks Chandler.  So with your fix, diamond now looks clean with AoS/SoA, but there remains an additional (and possibly unrelated) bug in SoA, correct?

**Comment by mcbennet** [comment] 2020-03-18 13:02
Yes, diamond looks clean to me. I am not yet sure however why my stochastic tests show failures for 1704 and Devel in AoS, but pass deterministic tests.

Also, SCO looks clean as well for AoS but SoA is still off. I do not know the nature of the SoA error in SCO.

**Comment by jtkrogel** [comment] 2020-03-18 13:11
Good to fix the manifesting issue, anyway.  The remaining SoA issue was introduced prior to 3.8.0, right?  I guess a return to the bisection search with SoA should be revealing.

**Comment by mcbennet** [comment] 2020-03-18 13:25
Follow up regarding deterministic tests.

@Hyeondeok-Shin , I modified your tests by increasing number of VMC walkers to 20 then removing targetwalkers variables in DMC sections, i.e.,

```
<qmc method="vmc" move="pbyp">
     <estimator name="LocalEnergy" hdf5="no"/>
     <parameter name="walkers">    20   </parameter>
     <parameter name="substeps">  1 </parameter>
     <parameter name="warmupSteps">  1  </parameter>
     <parameter name="steps">  1 </parameter>
     <parameter name="blocks">  1 </parameter>
     <parameter name="timestep">  1.0 </parameter>
     <parameter name="usedrift">   no </parameter>
   </qmc>

   <qmc method="dmc" move="pbyp" checkpoint="-1">
     <estimator name="LocalEnergy" hdf5="no"/>
     <parameter name="reconfiguration">   no </parameter>
     <parameter name="warmupSteps">  3  </parameter>
     <parameter name="timestep">  0.3 </parameter>
     <parameter name="steps">   3   </parameter>
     <parameter name="blocks">  10   </parameter>
     <parameter name="nonlocalmoves">  yes </parameter>
   </qmc>

   <qmc method="dmc" move="pbyp" checkpoint="-1">
     <estimator name="LocalEnergy" hdf5="no"/>
     <parameter name="reconfiguration">   no </parameter>
     <parameter name="warmupSteps">  3  </parameter>
     <parameter name="timestep">  0.002 </parameter>
     <parameter name="steps">   10   </parameter>
     <parameter name="blocks">  10   </parameter>
     <parameter name="nonlocalmoves">  yes </parameter>
   </qmc>
```

After doing so, I see that this deterministic tests agrees with my stochastic tests

| Build | Test Result |
|------|------------|
| 380 AoS real | REF |
| 380 AoS comp | REF |
| 380 SoA real | REF |
| 380 SoA comp | REF |
| 1704 AoS real | FAIL |
| 1704 AoS comp | FAIL |
| 1704 SoA real | FAIL |
| 1704 SoA comp | FAIL |
| Dev AoS real | FAIL |
| Dev AoS comp | FAIL |
| Dev SoA real | FAIL |
| Dev SoA comp | FAIL |
| DevMod AoS real | PASS |
| DevMod AoS comp | PASS |
| DevMod SoA real | FAIL |
| DevMod SoA comp | FAIL |

**Comment by jtkrogel** [comment] 2020-03-18 13:29
This is an important update to the deterministic test.  It's also consistent with the idea that only some trajectories (a subset of the phase space) are affected.

**Comment by mcbennet** [comment] 2020-03-18 13:50
More observations worth noting regarding the above deterministic test.

1. For AoS, all versions agree for series 1 -- the intermediate timestep.
2. For SoA, 1704 and 3.8.0 agree for series 1 while Dev and DevMod disagree with 3.8.0 for series 1.
3. Dev and DevMod agree with each other for series 1.

**Comment by prckent** [comment] 2020-03-18 15:08
Note that the VMC driver will round up the number of walkers to a multiple of the thread count. There is no way to change this because the existing VMC drivers require an equal number of walkers per thread, which makes sense from efficiency considerations although a route for more flexibility would be ideal. Therefore when specifying walkers you need to be careful about the number of threads that you use.

**Comment by mcbennet** [comment] 2020-03-18 15:13
For all of my tests of diamond 1x1x1, I have used 1 thread and 1 mpi task.

**Comment by prckent** [comment] 2020-03-24 20:50
Does the discussion above still reflect the current status?

**Comment by mcbennet** [comment] 2020-03-25 01:20
Some discussion has been continued within #2349. That WIP PR corresponds to the modifications that fixes AoS (mentioned above in present thread) -- though SoA remains broken.

**Comment by mcbennet** [comment] 2020-03-30 12:26
For comparison purposes, I am sharing an analogous plot here to the diamond 1x1x1 figure above but for SCO. This again suggests an underlying issue with SoA while AoS appears clean for version 3.8.0, then a bias in #1704 and beyond. The suggested modification in #2349 again appears to remove the bias in AoS.

![Energies_SCO](https://user-images.githubusercontent.com/1430804/77911834-7c3c2f00-725f-11ea-9d08-017930cf7d2c.png)

**Comment by jtkrogel** [comment] 2020-03-30 12:46
OK, so #2349 is a fix for the bug introduced in #1704 to AoS.  SoA has a different bug that predates version 3.8.0.

Interesting that both bugs, introduced separately, affect the total energy in a similar way.

Would you mind running SoA with 3.6.0 and 3.7.0?

**Comment by mcbennet** [comment] 2020-03-30 19:23
Submitted earlier today. Will prepend to the plot when complete.

**Comment by mcbennet** [comment] 2020-04-02 17:39
The discrepancy is also seen in 3.6.0 and 3.7.0

![Energies_SCO](https://user-images.githubusercontent.com/1430804/78280512-37c2c480-74e7-11ea-9862-43cfd5ed6e5a.png)

**Comment by mcbennet** [comment] 2020-04-08 11:35
The following figure contains corrected SrCoO3 data. In my previous figure, all SoA builds corresponded to the development branch by mistake.

![Energies_SCO](https://user-images.githubusercontent.com/1430804/78779569-29ebc400-796b-11ea-9eeb-f1b5b2fc2824.png)

From the statistical tests here, we see that a bug was introduced in #1704 and the bug remains in the current develop branch. #2349 fixes this bug.

**Comment by mcbennet** [comment] 2020-04-09 13:46
Regarding the deterministic test, here I focus on the absolute errors in the first DMC series. I have taken Hyeondeok's test and have varied two parameters independently -- (1) the number of target walkers in the DMC and (2) the timestep in the initial DMC. The plots below show the series 1 errors in total energy of 1704 and Develop (pulled in 3/13) w.r.t 3.8.0.

For all variations, it appears that 1704 is clean on this front. For Develop, clearly there is a dependence on both timestep and number of target walkers chosen -- also, from the case where targetwalkers=2 is is clear that the absolute error is not necessarily monotonic with timestep.

![2tw](https://user-images.githubusercontent.com/1430804/78901330-2f6a0c80-7a46-11ea-9f9a-54e2a03ae567.png)
![4tw](https://user-images.githubusercontent.com/1430804/78901333-3002a300-7a46-11ea-9b39-70cc71e4decd.png)
![8tw](https://user-images.githubusercontent.com/1430804/78901334-3002a300-7a46-11ea-8616-6169867c4bfe.png)

**Comment by mcbennet** [comment] 2020-04-09 18:59
PR #2177 appears to be the first to show the discrepancy from 3.8.0 for the first DMC series.
PR #2173 went in just before and it looks clean.

![8tw_New](https://user-images.githubusercontent.com/1430804/78930650-779f2400-7a72-11ea-929d-01a001ca9de5.png)

**Comment by prckent** [comment] 2020-04-13 13:25
After the additional fix of #2377, develop should now be cured of this important problem.

We can check the nightlies tomorrow afternoon for the results of the deterministic test, but I think we also need confirmation here that the problem is fixed in SrCoO3 and no other problems have crept in.

**Comment by ye-luo** [comment] 2020-04-13 13:31
@mcbennet could you verify that the develop no more diverge behaviour from v3.8.0?

**Comment by mcbennet** [comment] 2020-04-13 14:13
While SrCoO3 runs, I ran my most recent deterministic tests with diamond. So far, both DMC series are consistent with 3.8.0

![8tw_S1](https://user-images.githubusercontent.com/1430804/79127177-6a827d80-7d6f-11ea-98b0-11416db375f3.png)
![8tw_S2](https://user-images.githubusercontent.com/1430804/79127182-6bb3aa80-7d6f-11ea-8485-dff9db710bcc.png)

**Comment by mcbennet** [comment] 2020-04-15 12:17
The latest develop looks clean for this stochastic test.

![Energies_SCO](https://user-images.githubusercontent.com/1430804/79336261-6a11f000-7ef1-11ea-9720-84a8d5aeaa8d.png)

**Comment by prckent** [comment] 2020-04-17 23:31
From the above, I think we can happily mark this as closed. Thanks all.

**Closed by prckent** 2020-04-17 23:31 UTC
Labels: bug
