### ISSUE TITLE
3.12.0 release is broken: error: no matching member function for call to 'reextent'

### ISSUE THREAD

**Issue by yurivict** [QMCPACK/qmcpack#3698] opened 2022-01-01 19:40 UTC
```
In file included from /disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOASCII.cc:16:
In file included from /disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IO.h:20:
In file included from /disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOBase.h:26:
In file included from /disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOVar.h:20:
In file included from /disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOVarASCII.h:20:
In file included from /disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOVarBase.h:22:
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/Blitz.h:75:54: error: no matching member function for call to 'reextent'
        void resizeAndPreserve(sizes_type sizes){base_type::reextent(sizes);}
                                                 ~~~~~~~~~~~^~~~~~~~
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOVarASCII.h:352:14: note: in instantiation of member function 'Array<bool, 4, boost::multi::array<bool, 4>>::resizeAndPreserve' requested here
  ArrayValue.resizeAndPreserve(dims);
             ^
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOVarASCII.h:173:3: note: in instantiation of member function 'IO::IOVarASCII<bool, 4>::Resize' requested here
  IOVarASCII(std::string name) { Name = name; }
  ^
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/src/QMCTools/ppconvert/src/common/IOASCII.cc:621:35: note: in instantiation of member function 'IO::IOVarASCII<bool, 4>::IOVarASCII' requested here
        IOVarASCII<bool,4> *newVar = new IOVarASCII<bool,4>(name);
                                         ^
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/external_codes/boost_multi/multi/array.hpp:910:7: note: candidate function not viable: no known conversion from 'Array<bool, 4, boost::multi::array<bool, 4>>::sizes_type' (aka 'std::tuple<long, long, long, long>') to 'const typename array<bool, 4>::extensions_type' (aka 'const extensions_t<4L>') for 1st argument
        auto reextent(typename array::extensions_type const& x) -> array& {
             ^
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/external_codes/boost_multi/multi/array.hpp:941:7: note: candidate function not viable: requires 2 arguments, but 1 was provided
        auto reextent(typename array::extensions_type const& x, typename array::element const& e) -> array& {
             ^
```

clang-13
OS: FreeBSD 13

**Comment by prckent** [comment] 2022-01-01 20:27
Sorry about this Yuri! We have CI and nightlies with clang so i am puzzled how this got through, but clearly it did get through. Since the last release we have made building a previously optional utility (ppconvert) the default, and this is where the problem trips. Can you please add your cmake line and output?

I am traveling and so can't test the following, but perhaps try commenting out the ppconvert line on line 57 of https://github.com/QMCPACK/qmcpack/blob/develop/src/QMCTools/CMakeLists.txt to disable ppconvert. This would completely localize the error.

Interestingly clang13 is OK on develop, e.g. test output https://cdash.qmcpack.org/CDash/testDetails.php?test=13109421&build=278135, cmake output: https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=278134 ).

**Comment by yurivict** [comment] 2022-01-01 20:52
No problem!

Here is the [full build log](https://people.freebsd.org/~yuri/qmcpack-3.12.0.log).

**Comment by yurivict** [comment] 2022-01-01 21:10
Both clang 12 and 13 break the same way.

------

There is no particular urgency for me. I encountered this problem while trying to update the FreeBSD port ```science/qmcpack```.
Please take your time.

Thank you!
Yuri

**Comment by prckent** [comment] 2022-01-04 14:08
@correaa Since this traces to multi, and before we do any deeper investigation, can you guesstimate if there are any #ifdef I_AM_LINUX or #ifdef I_AM_BSD in multi that could cause this difference? Since the same compiler versions appear to work on Linux, presumably there is either a difference in multi or some contamination from system includes that is causing this issue.

**Comment by correaa** [comment] 2022-01-04 16:19
mmm. No, I don't make a conditional compilation depending on Linux vs BSD or anything like that. My first guess is that there is an accidental difference in the clang compilers in BSD. or in their corresponding STLs?

After all, I noticed lately that CMake can distinguish between clang and clang-apple, no?

maybe that's it, although the compiler is the same one could be compiling against libstd and the other against libc++.

**Comment by correaa** [comment] 2022-01-04 18:54
Sorry, I assumed this was an Apple computer. Is it? Is there a CI for Apple/BSD?

**Comment by yurivict** [comment] 2022-01-04 19:01
> Sorry, I assumed this was an Apple computer. Is it? Is there a CI for Apple/BSD?

No, this is FreeBSD.

**Comment by williamfgc** [comment] 2022-01-04 19:01
@correaa there is a CI job for [GitHub Actions Apple runners](https://github.com/QMCPACK/qmcpack/blob/develop/.github/workflows/ci-github-actions.yaml#L99) based on Accelerate. 

I'll try a FreeBSD VM to try to reproduce. Looks like there is an issue with unpacking (or packing) tuple arguments on that particular platform configuration:

```
/disk-samsung/freebsd-ports/science/qmcpack/work/qmcpack-3.12.0/external_codes/boost_multi/multi/array.hpp:910:7: note: candidate function not viable: no known conversion from 'Array<bool, 4, boost::multi::array<bool, 4>>::sizes_type' (aka 'std::tuple<long, long, long, long>') to 'const typename array<bool, 4>::extensions_type' (aka 'const extensions_t<4L>') for 1st argument
        auto reextent(typename array::extensions_type const& x) -> array& {
```

**Comment by correaa** [comment] 2022-01-04 19:11
Thank you, yes. It is also likely to be fixed in the last (tagged) version of Multi: https://gitlab.com/correaa/boost-multi/-/releases/v0.78 if you decide to update.

BTW, this version of Multi has a more CMake-friendly directory structure (basically the include files all or under repo/include/multi/*). It also has a proper CMakeLists.txt (if I got it right).

**Comment by prckent** [comment] 2022-01-04 22:26
Thanks @williamfgc . The puzzle to me is why tuples cause the problem on FreeBSD and no-where else that we know of...

If bumping the version of multi proves to be the solution, we could just push out a new release. The recently added QE7 support is a sufficient new capability that it is worth releasing.

**Comment by prckent** [comment] 2022-01-04 22:37
Note #3703

**Comment by williamfgc** [comment] 2022-01-05 17:41
FYI, this [libc++ issue](https://reviews.llvm.org/D96523?id=323162) might be related. There are tuple API changes in libc++ 13 [release notes](https://releases.llvm.org/13.0.0/projects/libcxx/docs/ReleaseNotes.html#api-changes).

**Comment by correaa** [comment] 2022-01-05 20:01
I understand is that BSD would be willing to jump to llvm as much as they can because GNU and BSD licenses are historically incompatible.

I am also bad at covering against libc++ because all my CI systems are linux. Is there a BSD system available in DockerHub that you can recommend, e.g. something that can be used as Debian? I am not familiar with BSD.

**Comment by yurivict** [comment] 2022-01-05 20:06
[Cirrus CI](https://cirrus-ci.org/guide/FreeBSD/)  supports FreeBSD.

**Comment by williamfgc** [comment] 2022-01-05 20:11
GitHub Actions has a [FreeBSD VM action](https://github.com/marketplace/actions/freebsd-vm) that runs on macOS hosts.

**Comment by correaa** [comment] 2022-01-05 20:18
Thank you for your help. 

Any idea why Boost.Test would fail to link when switching to libc++, https://gitlab.com/correaa/boost-multi/-/jobs/1945458031#L700

**Comment by PDoakORNL** [comment] 2022-01-05 20:27
I think there are likely to be other issues with libc++ and QMCPACK. My understanding was we don't officially support it.  I've never had success compiling with our offload offload or CUDA using libc++.

**Comment by PDoakORNL** [comment] 2022-01-05 20:27
All my clang builds use the gnu stdlibc++

**Comment by williamfgc** [comment] 2022-01-05 20:59
@correaa looks like ABI incompatibility on your boost libraries, I guess built with `libstdc++` and one of the reasons it's hard to mix with `libc` as @PDoakORNL pointed out. Having FreeBSD CI somehow would isolate LLVM from any GNU noise (including dependencies), but mixing toolchains can bring ABI problems on Linux (I was probably just lucky with QMCPACK). So far, I only found this problem and a missing `#include <array>` header in [HEGGrid.h](https://github.com/QMCPACK/qmcpack/blob/develop/src/QMCWaveFunctions/ElectronGas/HEGGrid.h).

**Closed** 2022-01-07 19:30 UTC
Labels: bug
