### ISSUE TITLE
Collectables weighting and "value_squared"

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#504] opened 2017-11-16 19:52 UTC
"Collectables" type estimators currently write both "values" and "values_squared" to the stat.h5 files.  Currently the only way to obtain correctly weighted mean values in DMC is to apply the weight by hand during Collectables accumulation.  This results in "values_squared" incorrectly containing a squared weight.

Two options: 1) delete value_squared and save 1/2 of the stat.h5 disk space (often GB's), 2) change the accumulation mechanism so that appropriate weights are applied to values and values_squared for each estimator (even on values, weights may be applied patchily).  

The potential value of keeping value_squared around is to have obtain better estimates of the variance of each quantity than can be obtained from the blocked sample variance.

**Comment by prckent** [comment] 2017-11-16 22:14
Two issues: correctness and affordability.

Since the values_squared is obviously wrong currently, can we safely conclude that no-one is using it?

**Comment by jtkrogel** [comment] 2017-11-17 12:33
I am not using it at present; I doubt if anyone else is.  It was really an attempt to use it that revealed that it is wrong, though it may be wrong in more ways than just the weighting.

@Paul-St-Young do you want to comment on what you are seeing w.r.t. the S(k) estimators?

**Comment by ye-luo** [comment] 2017-11-17 16:49
If we need to report an error bar on a quantity measured by estimators the weighted value_square is needed, I think we need to have the estimator manager properly handling the properly weighted value square. Dumping or not can be optional.

**Comment by Paul-St-Young** [comment] 2017-11-17 17:05
I recently experimented with obtaining `S(k)=<rho(k)rho(-k)>` from `rho(k)=a+ib`. Since `rho(-k)=a-ib`, `S(k)=<a^2>+<b^2>`. Namely, by recording `<a>` and `<b>` in value, value_squared will hold `<a^2>` and `<b^2>`. Thus `S(k)` can be reconstructed from `rho(k)`. This strategy is enabled by the SkAllEstimator dumping to hdf5 file.

I have created an example adapted from `tests/solids/bccH_3x3x3_ae/gamma_deriv.xml`. In particular, I have removed `<backflow>` and switched to the `pbyp` driver. I ran the example using the most recent develop branch (see `out`) and the example runs in a second, so please feel free to rerun.

What I found is that, the strategy I outlined above works in VMC but not in DMC. In the figure below, I show the S(k) and <rho(k)>^2 directly measured in `value` as dashed lines. The reconstructed S(k) is shown as the solid line. One can see that the solid line shifts from being close to S(k) in VMC to being close to <rho(k)>^2 in DMC. 
![vdmc_sk](https://user-images.githubusercontent.com/8060441/32959194-7d45d590-cb86-11e7-8244-a5d396e3853b.png)

I have tried removing the weight in the collectable estimator. The above plot did not change in a noticeable way. I think the weight is close to 1 anyway and is therefore not the cause of the observed difference. My guess is that block averaging is done differently in DMC than in VMC, but I am not quite sure how.

[bcc54.zip](https://github.com/QMCPACK/qmcpack/files/1483095/bcc54.zip)

**Comment by Paul-St-Young** [comment] 2017-11-17 17:07
Perhaps the block average is taken before the values have been squared?

**Comment by ye-luo** [comment] 2017-11-17 17:35
No. If I understand correctly, the logic of value and squared value is exactly the same as the LocalEnergy and LocalEnergy_sq in the scalar.dat. They are the weighted (both block and ensemble) average of the value and value_sq.
It seems to be that the value_sq is abused, you need record <a^2> as value.

**Comment by prckent** [comment] 2017-11-17 17:35
To follow-up Ye's comment: In the absence of squared values, to compute standard errors we can use reblocking or jack knife techniques.

**Comment by Paul-St-Young** [comment] 2017-11-17 17:54
@ye-luo If `value_square` of `<a>` is not really `<a^2>`, then why does the VMC reconstruction work?

**Comment by Paul-St-Young** [comment] 2017-11-17 17:58
Oh actually, it seems that block average is taken after squaring. That is why VMC reconstruction works. However, ensemble average is taken before squaring so the DMC reconstruction does not work.

I tried adding `<parameter name="walkers"> 16  </parameter>` to the VMC block and that broke the VMC reconstruction.

**Comment by Paul-St-Young** [comment] 2017-11-17 19:24
Well, here is a bit of good new. The LocalEnergy entry is unaffected by the ensemble average. Namely `value_squared` is actually `<a^2>`. This zeroth entry must be handled differently in the EstimatorManager.
![lsq](https://user-images.githubusercontent.com/8060441/32964874-3e6d1d38-cb9a-11e7-8b20-a8fda9bb5fa2.png)

I see no reason to keep `value_squared` if it does not record `<a^2>`. I think `value_squared` should either always record `<a^2>`, or be dropped completely.

**Comment by jtkrogel** [comment] 2017-11-17 19:25
Intended behavior first.  Isn't the point of `value_squared` to be able to compute:

`var(a) = <a^2>-<a>^2`

with `value` as `<a>` and `value_squared` as `<a^2>`?  If not, then __bug__.

**Comment by ye-luo** [comment] 2017-11-17 21:09
@Paul-St-Young Need to correct myself, you use of `value_squared` as `<a^2>` is correct. It is the weighted average of val^2, namely first square then average. I agree with @jtkrogel  if the code is doing averaging first and then taking square, there may be a bug.

**Comment by rcclay** [comment] 2017-11-20 23:58
I'm in favor of removing value_squared.  Accumulation and weighting of the collectables is so spread out between the Hamiltonian, QMCDriver, ParticleSet, and Estimator that it would take some nontrivial reworking to get value_squared to come out correctly.  Additionally, its been my experience that the improved estimate of the variance of observables obtained by measuring the variance per block is not worth the extra coding expense.  Note that scalar.dat files don't include this variance estimate except for LocalEnergy.

**Comment by Paul-St-Young** [comment] 2017-11-24 21:36
Looks like `value_squared` I/O is centralized in `QMCHamiltonian/observable_helper.h`.

`value_squared` can be eliminated by removing `H5Dwrite(value2_id...)` and surrounding statements. There are two occurrences, one in `observable_helper.h::read()`, the other in `observable_helper.h::write()`.

**Comment by prckent** [comment] 2017-12-11 14:36
I missed this discussion a few weeks back. I agree with @rcclay "its bad juju printing wrong things". Since the behavior is wrong and no one appears to need the functionality currently, let us simply not write value_squared. If needed later the implementation can be fixed.

Who would like to make the patch?

**Comment by Paul-St-Young** [comment] 2017-12-12 01:02
@prckent I would be happy to obliterate more code. I will submit a PR tonight.

**Comment by prckent** [comment] 2018-01-03 19:27
Fixed by @Paul-St-Young

**Closed by prckent** 2018-01-03 19:27 UTC
Labels: bug
