### ISSUE TITLE
nexus test issue

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1864] opened 2019-09-03 15:54 UTC
Since #1836
https://cdash.qmcpack.org/CDash/testDetails.php?test=6030711&build=77081
This seem caused by the introduce of new modules.
Test exception: "ImportError: cannot import name gcd"

**Comment by prckent** [comment] 2019-09-03 16:54
Perhaps bora needs a newer numpy?

If true, this also points to our need for a proper set of minimum versions & for nexus to check for them. Otherwise we get these errors that to the user will look like a bug of ours.

**Comment by prckent** [comment] 2019-09-03 16:54
Paging @jtkrogel  for comment.

**Comment by ye-luo** [comment] 2019-09-03 17:05
Yes. We need a policy.

**Comment by jtkrogel** [comment] 2019-09-03 19:10
The issue is the `gcd` function which was added to NumPy in version 1.15 (~July 2018).  Moving to wrap all numpy imports in the umbrella fashion, (i.e. `import numpy as np` then call `np.gcd` somewhere) would protect all the other parts of the code from failing here.

We do need to determine the minimum numpy version (and other modules) for Nexus as well as establish a policy for new additions.

For policy, I think we should hold at least to the "two year rule", so `gcd` is too new and should be replaced.  Suggestions for efficient ways to identify the minimum versions for library components imported into Nexus as it currently stands are welcome.

**Comment by jtkrogel** [comment] 2019-09-03 19:46
The Nox package looks like a good option for minimum version testing and/or enforcement:

https://nox.thea.codes/en/stable/

**Comment by prckent** [comment] 2019-09-03 20:23
- You can simply query the versions of the imported modules and quit if too old. Numpy seems to be the critical one - I believe it has been the source of *all* our python related versioning problems.
- For testing we can setup something using the minimum version.
- As a first step, we need to declare the minimum versions as we have for QMCPACK in a readme.md. Then we can update the CI and nightly tests appropriately.

**Comment by prckent** [comment] 2019-09-03 20:24
My reaction to nox: please no more packages or utilities. Lets do the simplest possible thing. We already know how to install exact versions of python and specific packages (e.g. with spack, we do this for oxygen nightlies). I don't want another dependency for something we have already solved.

**Comment by jtkrogel** [comment] 2019-09-03 20:26
I agree about query/test based on known minimum version.  If we have an easy way to scan over library (e.g. numpy) versions then we can determine what this is.  At present we do not even know what the minimum version is.

**Comment by prckent** [comment] 2019-09-03 21:51
1.13.2 was released  on 27 September 2017
1.13.1 was released on 6 July 2017

-> Given a release is upcoming,  see if 1.13.2 works

**Comment by jtkrogel** [comment] 2019-09-04 11:29
This is fine.  I was thinking along the lines of oldest working version rather than oldest supported version.

**Comment by jtkrogel** [comment] 2019-09-04 11:40
I will put in a fix for the current `gcd` issue.

@prckent I recall you posted somewhere about your recent experience installing specific python+numpy etc. versions with spack, but I can't find it at the moment.  Could you point me to that post/email?  I would like to install numpy 1.13.2 and iterate until there are no issues.

**Comment by prckent** [comment] 2019-09-04 17:54
See qmcpack/tests/test_automation/ornl_oxygen_setup.sh

This sets up the full environment used for nightly testing on oxygen via spack including python and python dependencies. You should be able to change numpy 1.16.4 to 1.13.2. The script does not setup a particular version of python for now, only the latest one implied by numpy, h5py etc. This could easily be refined if you have preferences.

**Comment by jtkrogel** [comment] 2019-09-04 18:02
Thanks.  I will have a look.

**Comment by prckent** [comment] 2019-09-11 14:32
I believe this was closed by #1879

**Closed by prckent** 2019-09-11 14:32 UTC
Labels: nexus
